config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users

  resources :categories, only: [:index, :show, :new, :create] do
    resources :transactions, only: [:index, :new, :create, :show]
  end

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :group_transactions, foreign_key: 'group_id'
  has_many :user_transaction_details, through: :group_transactions

  validates :name, presence: true
  validates :icon, presence: true

  ICONS_MAPPING = {
    'fas fa-folder' => 'Folder',
    'fas fa-star' => 'Star',
    'fas fa-heart' => 'Heart',
    'fas fa-globe' => 'Globe'
  }.freeze

  def icon_name
    ICONS_MAPPING[icon]
  end

  def total_amount
    user_transaction_details.sum(:amount)
  end
end

app/models/group_transaction.rb
class GroupTransaction < ApplicationRecord
  belongs_to :category, foreign_key: 'group_id'
  belongs_to :user_transaction_detail
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :user_transaction_details
  has_many :categories

  validates :name, presence: true
end

app/models/user_transaction_detail.rb
class UserTransactionDetail < ApplicationRecord
  belongs_to :user
  has_many :group_transactions
  has_many :categories, through: :group_transactions

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.includes(:user_transaction_details)
  end

  def show
    @category = Category.find(params[:id])
    @transactions = @category.user_transaction_details.order(created_at: :desc)
    @total_amount = @category.total_amount
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Category.includes(:user_transaction_details).find(params[:category_id])
    @transactions = @category.user_transaction_details.order(created_at: :desc)
    @total_amount = @category.total_amount
  end

  def new
    @category = Category.find(params[:category_id])
    @transaction = UserTransactionDetail.new
  end

  def create
    @category = Category.includes(:user_transaction_details).find(params[:category_id])
    @transaction = current_user.user_transaction_details.build(transaction_params)
    @transaction.group_transactions.build(category: @category)

    if @transaction.save
      redirect_to category_transactions_path(@category), notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:user_transaction_detail).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = current_user
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_transaction_details_helper.rb
module UserTransactionDetailsHelper
end

app/views/categories/index.html.erb
<%= stylesheet_link_tag 'mystyle' %>
<main>
  <div class="log-in">
    <%= link_to root_path, class: "fas fa-arrow-left custom-arrow" do %>
    <% end %>
    <h2 class="regTitle">CATEGORIES</h2>
  </div>
  <div class="d-flex flex-row-reverse bd-highlight" style="background-color:#3778c2">
    <div class="p-2 bd-highlight" style="color:#9cb8db">Most ancient</div>
    <div class="p-2 bd-highlight" style="color:#c1d2e8">Most recent</div>
  </div>

  <div class="d-flex flex-row-reverse bd-highlight bg-white">
    <div class="p-2 bd-highlight">$00.0</div>
    <div class="p-2 bd-highlight">Gift credit</div>
  </div>
  <hr/>
  <br/>
<div class="d-flex flex-column align-item-center" >
<% @categories.each do |category| %>
<%= link_to  category_transactions_path(category), style: "text-decoration: none; color: inherit;"  do %>
  <div class="category">
  <i class="<%= category.icon %> custom-icon fa-2x" ></i>
  <h2 class="catName"><%= category.name %></h2>
    
  <p class="catAmount">Total Amount: <%= number_to_currency(category.total_amount) %></p>
    
  </div>
  <% end %>
  <hr/>
<% end %>

</div>

 <br/>
 
  <div class="p-2 d-flex justify-content-center cutomAddCatBtn" style="background-color:#5fb523">
    <%= link_to "Add a new category", new_category_path(current_user), class: "btn border border-white text-white"%>
  </div>
</main>

app/views/categories/new.html.erb
<%= stylesheet_link_tag 'mystyle' %>
  <div class="log-in">
    <%= link_to categories_path, class: "fas fa-arrow-left custom-arrow" do %>
    <% end %>
    <h2 class="regTitle">New Category</h2>
  </div>
  <div class="d-flex flex-row-reverse bd-highlight" style="background-color:#3778c2">
    <div class="p-2 bd-highlight" style="color:#9cb8db">Most ancient</div>
    <div class="p-2 bd-highlight" style="color:#c1d2e8">Most recent</div>
  </div>

  <div class="d-flex flex-row-reverse bd-highlight bg-white">
    <div class="p-2 bd-highlight">$00.0</div>
    <div class="p-2 bd-highlight">Gift credit</div>
  </div>
  <hr/>
  <br/>

<%= form_for @category, url: categories_path, html: { class: 'my-4' } do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br/>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Category Name" %>
  </div>

  <br>
  <div class="mb-3">
    <%= f.label :icon, class: 'form-label' %>
    <%= f.select :icon, Category::ICONS_MAPPING.keys.map { |key| [Category::ICONS_MAPPING[key], key] }, { prompt: 'Select an icon' }, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= f.submit "Create Category", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<p>Icon: <%= @category.icon %></p>
<p>Total Amount: <%= @category.total_amount %></p>
<!-- Add any other information you want to display -->

app/views/groups/index.html.erb
<!-- app/views/user_transaction_details/groups.html.erb -->
<h1>User Transaction Details Groups</h1>

<% @groups.each do |group| %>
  <div>
    <h2><%= group.name %></h2>
    <p>Icon: <%= group.icon %></p>
    <p>Total Amount: <%= group.user_transaction_details.sum(:amount) %></p>
    <%= link_to 'View Transactions', category_path(group) %>
  </div>
<% end %>

<%= link_to 'Back to Categories', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "mystyle", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>

     <% if user_signed_in? %>
      <nav class="nav-container">
        <div class="left-menu">
          <% if user_signed_in? %>
            <form action="<%= destroy_user_session_path %>" method="post">
              <input type="hidden" name="_method" value="delete">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
           <span class="user" > 
           <i class="fas fa-bars"></i>
           <i class="fas fa-search search-icon"></i>
            </span>
            
            </form>

          <% end %>
        </div>
      </nav>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1 class="appTitle">Welcome to Budget App</h1>

<button class="btn btn-primary log-in"><%= link_to 'Log in', new_user_session_path, style: 'text-decoration: none;'  %></button>
<button class="btn btn-primary sign-up"><%= link_to 'Sign up', new_user_registration_path, style: 'text-decoration: none;'  %></button>

</div>

app/views/transactions/_form.html.erb
<%= form_for [@category, @transaction] do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div>
    <%= f.label :category_ids %>
    <%= f.collection_select(:category_ids, @categories, :id, :name) %>
  </div>

  <%= f.submit 'Save' %>
<% end %>

app/views/transactions/index.html.erb
  <%= stylesheet_link_tag 'mystyle' %>
  <div class="log-in">
    <%= link_to categories_path, class: "fas fa-arrow-left custom-arrow" do %>
    <% end %>
    <h2 class="regTitle">TRANSACTIONS</h2>
  </div>
  <div class="d-flex flex-row-reverse bd-highlight" style="background-color:#3778c2">
    <div class="p-2 bd-highlight" style="color:#9cb8db">Most ancient</div>
    <div class="p-2 bd-highlight" style="color:#c1d2e8">Most recent</div>
  </div>

  <div class="d-flex flex-row-reverse bd-highlight bg-white">
    <div class="p-2 bd-highlight">$00.0</div>
    <div class="p-2 bd-highlight">Gift credit</div>
  </div>
  <hr/>
  <br/>


<br/>
<br/>


<div class="d-flex flex-column align-item-center" > 
      <% @transactions.each do |transaction| %>
      <div class="category">
          <i class="<%= @category.icon %> custom-icon fa-2x" ></i>
          <h2 class="catName"><%= transaction.name %></h2>
          <strong><%= number_to_currency(transaction.amount) %></strong>
          <br>  
      </div>
      <div class="transAt"><p><%= transaction.created_at %></p></div>
       <hr/>
      <% end %>
     
</div>
<br/>
<div class="p-2 d-flex justify-content-center cutomAddCatBtn" style="background-color:#5fb523">
<%= link_to "Add a new transaction", new_category_transaction_path(@category), class: "btn border border-white text-white" %>
</div>

app/views/transactions/new.html.erb
<%= stylesheet_link_tag 'mystyle' %>
<div class="log-in">
  <%= link_to category_transactions_path(@category), class: "fas fa-arrow-left custom-arrow" do %>
  <% end %>
  <h2 class="regTitle">New Transaction </h2>
</div>
<div class="d-flex flex-row-reverse bd-highlight" style="background-color:#3778c2">
  <div class="p-2 bd-highlight" style="color:#9cb8db">Most ancient</div>
  <div class="p-2 bd-highlight" style="color:#c1d2e8">Most recent</div>
</div>

<div class="d-flex flex-row-reverse bd-highlight bg-white">
  <div class="p-2 bd-highlight">$00.0</div>
  <div class="p-2 bd-highlight">Gift credit</div>
</div>
<hr/>
<br/>

<%= form_with(model: [@category, @transaction], url: category_transactions_path(@category), method: :post) do |form| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br/>
  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, required: true, placeholder: "Transaction Title" %>
  </div>

  <br/>
  <div class="mb-3">
    <%= form.label :amount %>
    <%= form.number_field :amount, required: true %>
  </div>

  <br/>
  <div class="mb-3">
  <%= form.label :category_id, "Category" %><br>
  <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a category" }, { required: true } %>  
  </div>

  <br/>
  <div class="mb-3">
    <%= form.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/transactions/show.html.erb
<!-- app/views/transactions/show.html.erb -->
<h1>Transactions for <%= @category.name %></h1>

<p>Total Amount: <%= @total_amount %></p>

<% @transactions.each do |transaction| %>
  <div class="transaction">
    <p><strong><%= transaction.name %></strong> - <%= transaction.amount %></p>
    <!-- Add any other transaction details you want to display -->
  </div>
<% end %>

<%= link_to 'Add a new transaction', new_category_transaction_path(@category), class: 'btn btn-primary' %>
<%= link_to 'Back', root_path, class: 'btn btn-secondary' %>

app/views/users/index.html.erb
<h1>welcome to user screen</h1>